//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dabay6.Android.ContentProvider.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dabay6.Android.ContentProvider.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {0}.{1};
        ///
        ///public interface ColumnMetadata {{
        ///    public int getIndex();
        ///
        ///    public Boolean isForeign();
        ///
        ///    public String getName();
        ///
        ///    public String getType();
        ///}}.
        /// </summary>
        internal static string column_metadata {
            get {
                return ResourceManager.GetString("column_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error writting configuration file to disk.
        /// </summary>
        internal static string ConfigurationFileError {
            get {
                return ResourceManager.GetString("ConfigurationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright (c) 2013 Remel Pugh
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * 	http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software 
        /// * distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        /// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        /// * See the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contract_class {
            get {
                return ResourceManager.GetString("contract_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	/**
        ///	 * Created in version {14}
        ///	 */
        ///    public static final class {0} extends {1}Contract {{
        ///        public static final String TABLE_NAME = &quot;{2}&quot;;
        ///        public static final Uri CONTENT_URI = Uri.parse({1}Contract.CONTENT_URI + &quot;/&quot; + TABLE_NAME);
        ///        public static final String[] PROJECTION = new String[] {{
        ///{6}
        ///        }};
        ///        public static final String TYPE_DIR_TYPE = &quot;vnd.android.cursor.dir/{3}-{4}&quot;;
        ///        public static final String TYPE_ELEM_TYPE = &quot;vnd.android.cursor.item/{3}-{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string contract_subclass {
            get {
                return ResourceManager.GetString("contract_subclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            if (oldVersion &lt;= {0}) {{
        ///                db.execSQL(&quot;CREATE TABLE &quot; + TABLE_NAME + &quot;_tmp (&quot; + {1}{2} + &quot;);&quot;);
        ///                db.execSQL(&quot;INSERT INTO  &quot; + TABLE_NAME + &quot;_tmp SELECT &quot; + {3} + &quot; FROM &quot; + TABLE_NAME + &quot;;&quot;);
        ///                db.execSQL(&quot;DROP TABLE &quot; + TABLE_NAME + &quot;;&quot;);
        ///                db.execSQL(&quot;ALTER TABLE &quot; + TABLE_NAME + &quot;_tmp RENAME TO &quot; + TABLE_NAME + &quot;;&quot;);
        ///
        ///                oldVersion = {0};
        ///            }}.
        /// </summary>
        internal static string contract_subclass_upgrade {
            get {
                return ResourceManager.GetString("contract_subclass_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright (c) 2013 Remel Pugh
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * 	http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software 
        /// * distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        /// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        /// * See the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string database_helper {
            get {
                return ResourceManager.GetString("database_helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {0}.data.DTO;
        ///
        ///import android.content.ContentValues;
        ///import android.database.Cursor;
        ///import android.os.Parcel;
        ///import android.os.Parcelable;
        ///import android.text.TextUtils;
        ///import {6};
        ///import com.google.gson.Gson;
        ///import com.google.gson.GsonBuilder;
        ///
        ///@SuppressWarnings(&quot;unused&quot;)
        ///public class {1}DTO implements Parcelable {{
        ///    public static final Parcelable.Creator&lt;{1}DTO&gt; CREATOR = new Parcelable.Creator&lt;{1}DTO&gt;() {{
        ///        public {1}DTO createFromParcel(final Parcel in) {{
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dto_class {
            get {
                return ResourceManager.GetString("dto_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     public {2} {3}{0}() {{
        ///        return {1};
        ///    }}
        ///
        ///    public void {4}{0}(final {2} value) {{
        ///        {1} = value;
        ///    }}.
        /// </summary>
        internal static string dto_class_getset {
            get {
                return ResourceManager.GetString("dto_class_getset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///        index = cursor.getColumnIndex(Columns.{0}.getName());
        ///        if (index != -1) {{
        ///            {1}.{2}{3}(cursor.get{4}(index));
        ///        }}.
        /// </summary>
        internal static string dto_class_load {
            get {
                return ResourceManager.GetString("dto_class_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code generation has finisehd, do wish to exit?.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 return builder.table({0}){1};
        ///.
        /// </summary>
        internal static string expanded_selection {
            get {
                return ResourceManager.GetString("expanded_selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 final String id = uri.getPathSegments().get(1);
        ///
        ///                return builder.table({0}){1}.where(&quot;{2}.&quot; + uriType.getIdColumnName() + &quot; = ?&quot;, id);
        ///.
        /// </summary>
        internal static string expanded_selection_id {
            get {
                return ResourceManager.GetString("expanded_selection_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to generate the content provider.
        /// </summary>
        internal static string GenerateContentProvider {
            get {
                return ResourceManager.GetString("GenerateContentProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright (c) 2013 Remel Pugh
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * 	http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software 
        /// * distributed under the License is distributed on an &quot;AS IS&quot; BASIS, 
        /// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
        /// * See the  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string provider {
            get {
                return ResourceManager.GetString("provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                 case {0}: {{
        ///                    insertStmt = db.compileStatement({1}.getBulkInsertString());
        ///
        ///                    for (final ContentValues value : values) {{
        ///                        {1}.bindValuesInBulkInsert(insertStmt, value);
        ///                        insertStmt.execute();
        ///                        insertStmt.clearBindings();
        ///                    }}
        ///
        ///                    insertStmt.close();
        ///
        ///                    db.setTransactionSuccessful();
        ///
        ///                    numberInserted = v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string provider_bulk {
            get {
                return ResourceManager.GetString("provider_bulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to package {0}.{1};
        ///
        ///import android.content.ContentValues;
        ///import android.database.Cursor;
        ///import android.database.sqlite.SQLiteDatabase;
        ///import android.text.TextUtils;
        ///
        ///import java.util.*;
        ///
        ////**
        /// * SelectionBuilder
        /// */
        ///@SuppressWarnings(&quot;unused&quot;)
        ///public class SelectionBuilder {{
        ///    private final Map&lt;String, String&gt; projectionMap = new HashMap&lt;String, String&gt;();
        ///    private final StringBuilder selection = new StringBuilder();
        ///    private final ArrayList&lt;String&gt; selectionArgs = new ArrayList&lt;Str [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string selection_builder {
            get {
                return ResourceManager.GetString("selection_builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to upgrade existing JSON file, choose NO to overwite file.
        /// </summary>
        internal static string UpgradeJsonFile {
            get {
                return ResourceManager.GetString("UpgradeJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Copyright (c) 2013 Remel Pugh
        /// *
        /// * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        /// * you may not use this file except in compliance with the License.
        /// * You may obtain a copy of the License at
        /// *
        /// * 	http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Unless required by applicable law or agreed to in writing, software
        /// * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
        /// * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        /// * See the Lic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string uri_type {
            get {
                return ResourceManager.GetString("uri_type", resourceCulture);
            }
        }
    }
}
